services:
  mongo-home:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_home_data:/data/db

  mysql-tenant:
    image: mysql:latest
    ports:
      - 3333:3306
    volumes:
      - mysql_tenant_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-contract:
    image: mysql:latest
    ports:
      - 3334:3306
    volumes:
      - mysql_contract_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mongo-maintenance:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_maintenance_data:/data/db

  mysql-payment:
    image: mysql:latest
    ports:
      - 3335:3306
    volumes:
      - mysql_payment_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  contract-service:
    image: sanderjannes/contract-service
    ports:
      - 8086:8086
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-contract
      MYSQL_DB_PORT: 3306
      TENANT_SERVICE_BASEURL: tenant-service:8082
      PAYMENT_SERVICE_BASEURL: payment-service:8084
    depends_on:
      - mysql-contract
      - home-service
      - tenant-service

  home-service:
    image: sanderjannes/home-service
    ports:
      - 8081:8081
    environment:
      MONGO_DB_HOST: mongo-home
      MONGO_DB_PORT: 27017
      MAINTENANCE_SERVICE_BASEURL: maintenance-service:8083
    depends_on:
      - mongo-home
      - maintenance-service
    
  maintenance-service:
    image: sanderjannes/maintenance-service
    ports:
      - 8083:8083
    environment:
      MONGO_DB_HOST: mongo-maintenance
      MONGO_DB_PORT: 27017
    depends_on:
      - mongo-maintenance

  tenant-service:
    image: sanderjannes/tenant-service
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-tenant
      MYSQL_DB_PORT: 3306
    depends_on:
      - mysql-tenant
  
  payment-service:
    image: sanderjannes/payment-service
    ports:
      - 8084:8084
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-payment
      MYSQL_DB_PORT: 3306
    depends_on:
      - mysql-payment

  api-gateway:
    depends_on:
      - home-service
      - tenant-service
      - contract-service
    image: sanderjannes/api-gateway
    ports:
      - 8085:8085
    links:
      - home-service
      - tenant-service
      - contract-service
    environment:
      HOME_SERVICE_BASEURL: home-service:8081
      TENANT_SERVICE_BASEURL: tenant-service:8082
      CONTRACT_SERVICE_BASEURL: contract-service:8086

  rental-application:
    depends_on:
      - api-gateway
    image: sanderjannes/rental-application
    ports:
      - 8080:8080
    links:
      - api-gateway
    environment:
      API_GATEWAY_BASEURL: api-gateway:8085

volumes:
  mongodb_home_data:
  mysql_tenant_data:
  mysql_contract_data:
  mongodb_maintenance_data:
  mysql_payment_data: