server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email

      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: home-service-all
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/homes/all
            - Method=GET
          filters:
            - SetPath=/api/home/all

        - id: home-service-available
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/homes
            - Method=GET
          filters:
            - SetPath=/api/home/available

        - id: home-service-details
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/home/{id}/details
            - Method=GET
          filters:
            - RewritePath=/home/?(?<id>.*)/details, /api/home/$\{id}/details

        - id: contract-service-all-by-home
          uri: http://${CONTRACT_SERVICE_BASEURL:localhost:8086}
          predicates:
            - Path=/home/{id}/contracts/all
            - Method=GET
          filters:
            - RewritePath=/home/?(?<id>.*)/contracts/all, /api/contract/home/$\{id}/all

        - id: contract-service-current-by-home
          uri: http://${CONTRACT_SERVICE_BASEURL:localhost:8086}
          predicates:
            - Path=/home/{id}/contracts/current
            - Method=GET
          filters:
            - RewritePath=/home/?(?<id>.*)/contracts/current, /api/contract/home/$\{id}/current

        - id: home-service-post
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/home
            - Method=POST
          filters:
            - SetPath=/api/home

        - id: home-service-put-delete
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/home/{id}
            - Method=GET, PUT, DELETE
          filters:
            - RewritePath=/home/?(?<id>.*), /api/home/$\{id}
