server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: home-service-all
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/homes
            - Method=GET
          filters:
            - SetPath=/api/home/all

        - id: contract-service-per-home
          uri: http://${CONTRACT_SERVICE_BASEURL:localhost:8086}
          predicates:
            - Path=/home/{id}/contracts
            - Method=GET
          filters:
            - RewritePath=/home/?(?<id>.*)/contracts, /api/contract/home/$\{id}

        - id: home-service-post
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/home
            - Method=POST
          filters:
            - SetPath=/api/home

        - id: home-service-put-delete
          uri: http://${HOME_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/home/{id}
            - Method=PUT, DELETE
          filters:
            - RewritePath=/home/?(?<id>.*), /api/home/$\{id}

        - id: tenant-service
          uri: http://${TENANT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tenants
            - Method=GET
          filters:
            - SetPath=/api/tenant/all
